### ISSUE TITLE
Markdown Format also formats tables.

### ISSUE THREAD

**Issue by dmitshur** [fcrespo82/atom-markdown-table-formatter#1]
Hi there,

Just as a heads up in case you're not aware, there's a Markdown Format package that formats tables as well. I'm curious what you think of it.

https://atom.io/packages/markdown-format

For example,

``` Markdown
| Branch  | Behind | Ahead |
|---------|-------:|:------|
| improve-nested-list-support | 1 | 1 |
| **master** | 0 | 0 |
```

That will become this when on save:

``` Markdown
| Branch                      | Behind | Ahead |
|-----------------------------|-------:|:------|
| improve-nested-list-support |      1 | 1     |
| **master**                  |      0 | 0     |
```

Thanks.

**Comment by slang800** [comment]
@fcrespo82 - I'd be interested in joining forces. I've been working on a package called [tidy-markdown](https://atom.io/packages/tidy-markdown). While it's not nearly as configurable as yours (I've been aiming to be more like gofmt and establish a simple [canonical representation](https://github.com/slang800/markdown-styleguide) of markdown), it does share similar goals. Plus I format headers in the same way, so I think you'll like it :wink:.

**Comment by fcrespo82** [comment]
This is nice, what do you have in mind?

Sure I will help whenever I can, but I recently changed some of my work to VSCode since it runs much more smoothly on my work machine. But it can be good too. Maybe we could have the plugin for Code too...
