### ISSUE TITLE
Can not recognize some format

### ISSUE THREAD

**Issue by arielyang** [fcrespo82/atom-markdown-table-formatter#11]
aaa|dafdas|adfas
----\t| ----\t| ---
asdf|asadf|sdfas

will be formated to:

aaa|dafdas|adfas
----\t| ----\t:-----
 asdf

**Comment by lierdakil** [comment]
It should be good to publish. Reopening until fix is live.

**Comment by fcrespo82** [comment]
It's LIVE!

**Comment by arielyang** [comment]
cool
