### ISSUE TITLE
provide more info in readme

### ISSUE THREAD

**Issue by alsotang** [fcrespo82/atom-markdown-table-formatter#19]
This plugin is awesome, I just download it and use in my atom.

Some suggestions:

1. provide some usage info in readme.
    when I download it, I exactly dont know how it works. Though I can inspect its atom setting to see what would hapenning. but to a new user, he would just go and find another one.
2. a screenshot of atom setting

**Comment by fcrespo82** [comment]
Thanks for your feedback. I'll add some usage info in readme soon.

**Comment by fcrespo82** [comment]
Release 2.5.5 resolves this, if you find anything useful that I should add please let me know.
