### ISSUE TITLE
Get poor looks with non-monospace fonts

### ISSUE THREAD

**Issue by reverland** [fcrespo82/atom-markdown-table-formatter#20]
I'm curious why it not works for me then I found...I use a non-monospaced font.

![screenshot from 2015-11-19 00 03 37](https://cloud.githubusercontent.com/assets/1418726/11246066/05e76668-8e51-11e5-9a9c-5177b47e1bf1.png)

However, its the beyond the web techniques, so maybe we can achieve a better looking formater for not monospace fonts.

I dont know if its a considerable thoughts.: )

**Comment by lierdakil** [comment]
It's not a great idea to use non-monospace font with Markdown or source code editor. There are many decent-looking free monospace fonts out there, and I highly recommend you take a look around.

Some examples from the top of my head (in no particular order):
- [DjVu Sans Mono](http://dejavu-fonts.org/)
- [Fira Mono](https://mozilla.github.io/Fira/)
- [Source Code Pro](https://adobe-fonts.github.io/source-code-pro/)
- [Anonymous Pro](http://www.marksimonson.com/fonts/view/anonymous-pro)
- [Droid Sans Mono](https://www.google.com/fonts/specimen/Droid+Sans+Mono)
- [Liberation Mono](https://fedorahosted.org/liberation-fonts/)

It could be possible to slap together a grammar that would highlight those tables and a stylesheed that would apply monospace font to those, but... let's just say this would be far from optimal.

**Comment by fcrespo82** [comment]
Yep, I agree with @lierdakil. I would recomment to use a monospace font instead.

**Comment by reverland** [comment]
@fcrespo82 @lierdakil Thanks, I'd like to close this issue,
But maybe as a reminder for someone can't figure out why it isn't work as intended...: )

**Comment by lierdakil** [comment]
Actually, after looking at gfm grammar one more time, it already defines table spans. So you can conceivably add something like this to your stylesheet, if you really want to:

```css
atom-text-editor::shadow .table.gfm {
    font-family: monospace;
}
```

I still don't think this is a great solution, but hey, you're free to do whatever you want ;) 

Note: I don't think we should add this to package stylesheet, for a variety of reasons. But maybe we could add this trick into readme?

**Comment by reverland** [comment]
@lierdakil 

Wowoww...Awesome!!! Its an interesting trick: )

Yeah, I tried it and found adding this to stylesheet may cause misplacement of lines or words, make the page looks a little strange if you choose a quite different font from monospace with other content. 

Thank you lierdakil, atom is really a customizable editor!
