### ISSUE TITLE
Setting for enabling and disabling auto left justify tables

### ISSUE THREAD

**Issue by jonleung** [fcrespo82/atom-markdown-table-formatter#21]
Instead of tables being automatically left justified, it would be great if you could have a setting to choose whether you want your tables to be left justified. For context, the style guide for markdown that my team follows does not allow for the left justification.

**Comment by fcrespo82** [comment]
I think this makes sense as a configure option. I'm on a vacation right now so don't expect that just now. After 12/11 I'll be back from vacation and will issue an update with such code.

Thanks for using my package.

Best regards!

--

Fernando X. F. Crespo

**Comment by jonleung** [comment]
Absolutely love it! Thanks!

—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by fcrespo82** [comment]
This is now up in 2.7.0

Hope you like it.
