### ISSUE TITLE
Only works with default language-gfm grammar, should work with custom grammar

### ISSUE THREAD

**Issue by winterflags** [fcrespo82/atom-markdown-table-formatter#22]
The Table Formatter doesn’t work for me. I installed it just now, so I'm not sure if it has to do with the current version of Atom or anything else.

I'm editing a `.markdown` file and used Dr.Drang's test table:

```markdown
|Left align|Right align|Center align|
|:---------|----------:|:----------:|
|This|This|This|
|column|column|column|
|will|will|will|
|be|be|be|
|left|right|center|
|aligned|aligned|aligned|
```

Neither the keyboard shortcut or the context menu options work for me.

System: OS X 10.11
Atom: 1.3.1

**Comment by fcrespo82** [comment]
Could you elaborate?

I'm not able to reproduce this error.

**Comment by fnurl** [comment]
I'm having the same issue. I open a new file, paste the table included by the OP and run the command and nothing happens. Running Atom 1.5.3 on OS X 10.11.3.

Is the package dependent on a specific syntax scope?

**Comment by fcrespo82** [comment]
Sorry, but I am unable to reproduce this error.

System: Ubuntu 15.04
Atom version: gif recorded on 1.4.0, but tested on 1.5.3 as well
Package version: 2.7.2

![atom-markdown-table-formatter](https://cloud.githubusercontent.com/assets/462171/13264894/06298f9e-da4f-11e5-8c0b-b3166fd718c5.gif)

**Comment by fnurl** [comment]
Ok, I found out why it does not work. If the `language-gfm` package is not enabled, it does not work. I use the `language-markdown` package which recommends turning off language-gfm. I also use other markdown packages when writing: `language-pfm` and `atom-language-madoko`.

Is it possible to remove the `language-gfm` dependency?

**Comment by lierdakil** [comment]
We could probably add config option for specifying what grammars are treated as Markdown. Just enabling it for *all* grammars could have unintended side effects.
