### ISSUE TITLE
Error formatting tables with empty header

### ISSUE THREAD

**Issue by lierdakil** [fcrespo82/atom-markdown-table-formatter#24]
Due to changes to regex introduced by d992e945, tables with empty headers are misformatted, e.g.

```
|
|-|-|-|-|
|table | with |empty |header|
```

is formatted like

```
|:----------------------------|
| -|-|-|-                     |
| table | with |empty |header |
```

I'd fix this silently, but I wonder if we should merge `editor-tests` branch while at it. I'll submit a PR shortly.

**Comment by fcrespo82** [comment]
Closed by #25
