### ISSUE TITLE
Mangles the second table

### ISSUE THREAD

**Issue by kjknudsen** [fcrespo82/atom-markdown-table-formatter#26]
If I have a file like this, your formatter works great on the first table, but the second is mangled.
# Header

| Name | Phone | Email |
| :-- | :-- | :-- |
| Name | 111 | abc |
# Header 2

| Name | Phone | Email |
| :-- | :-- | :-- |
| Name | 222 |  |

**Comment by lierdakil** [comment]
I'm not sure I can see the problem here.

Provided input:

```
# Header

| Name        | Phone            | Email                        |
|:------------|:-----------------|:-----------------------------|
| Name | 111      | abc  |

# Header 2

| Name       | Phone        | Email |
|:-----------|:-------------|:------|
| Name | 222 |       |
```

Resulting output:

```
# Header

| Name | Phone | Email |
|:-----|:------|:------|
| Name | 111   | abc   |

# Header 2

| Name | Phone | Email |
|:-----|:------|:------|
| Name | 222   |       |
```

Looks fine to me.

**Comment by kjknudsen** [comment]
Here's what I get with version 2.7.2 of markdown-table-formatter installed
on version 1.4.0 of Atom.

# Header

| Name | Phone | Email |
|:-----|:------|:------|
| Name | 111   | abc   |

# Header 2| Name | Phone | Email |
|:-----|:------|:------|
| Name | 222   |       |
|

**Comment by lierdakil** [comment]
Hmm. Just updated to 1.4.0, still can't reproduce.

**Comment by lierdakil** [comment]
Maybe you could upload a test file somewhere?

**Comment by momocus** [comment]
I have encounter the same issue.

**Comment by arthur-tse7** [comment]
Since this doesn't look like it's been fixed, I'll add an example. I believe it the formatter doesn't know when a table ends and it tries to take the lines after as well.

**Not formatted:**
```
## Header

|    |    |    |
|:---|:---|:---|
|    |    |    |
|    |    |    |

## Header 2

  |   |  
--|---|--
  |   |  
  |   |  
```

**Format Try 1:**
```
## Header

|    |    |    |
|:---|:---|:---|
|    |    |    |
|    |    |    |

## Header 2|    |    |    |
|:---|:---|:---|
|    |    |    |
|    |    |    |
 |  
```

**Format Try 2:**
```
## Header

|    |    |    |
|:---|:---|:---|
|    |    |    |
|    |    |    ||  ## Header 2  |    |  |  |
|:--------------|:---|:----|
|               |    |     |
|               |    |     |
|               |    |     |
 |  
```

**Format Try 3:**
```
## Header

|                   |        |                              |
|:------------------|:-------|:-----------------------------|
|                   |        |                              |
|                   |        |  ||  ## Header 2  |    |  |  |
|  :--------------  |  :---  |  :----                       |
|                   |        |                              |
|                   |        |                              |
|                   |        |                              |
|                   |        |                              |

```

**Format Try 4:**
Nothing changes.

**Comment by fcrespo82** [comment]
@arthur-tse7 I still couldn't reproduce. 
Atom: 1.12.7
Package version: 2.8.3
Attached a gif to demonstrate
![anim](https://cloud.githubusercontent.com/assets/462171/21147581/a58fff1c-c13c-11e6-80cd-134b7000d286.gif)

**Comment by matt-hoiland** [comment]
Try it in CRLF mode. Pretty sure that's how it can be reproduced.

Now I hate CRLF mode as much as the next guy, but you need to support all line endings.

**Comment by lierdakil** [comment]
Nope, can't repro in CRLF mode. Atom normalizes CRLF to just LF.

**Comment by lierdakil** [comment]
Wait, no, spoke too soon. It reproduces under *some* circumstances. Not sure which exactly.
