### ISSUE TITLE
Formatting is wrong unless you select an empty line before and after table

### ISSUE THREAD

**Issue by rgregg** [fcrespo82/atom-markdown-table-formatter#27]
I turn off auto-save and auto-select whole document because I don't want all the tables updated in a file when I change one place, so that's the basis for this issue.

Now, let's say you have a document that looks like this:

```
#table 2

| abc | def |
|---|---|
| asdlkjalkdjalksdj | alksdjalskdj |
```

Since I have to select the rows that I want formatted, I usually select the three rows that make up the table. That results in this output for me with the latest release (2.7.2):

```
#table 2

| abc | def |
|:------------------|:-------------|
| asdlkjalkdjalksdj | alksdjalskdj |

```

Note that the column headers didn't get properly sizes and there's an extra empty line after the table that wasn't there before.

If I select the line above the table, the table, and an empty line below the table, then I get the expected output. If I don't select an empty line above the table, the headers are wrong. If I don't select an empty line after the table, then it adds one.

**Comment by fcrespo82** [comment]
What is your Atom version, and OS?
I do see the line being added to the end, but my table formats just fine.

**Comment by fcrespo82** [comment]
I've just updated to Atom 1.4.0 and couldn't reproduce the bug.

The line added to the final of the document is from Atom itself. You can test it by disabling the package and saving the document.

**Comment by lierdakil** [comment]
Same here, can't repro on Atom 1.4.0.
