### ISSUE TITLE
Problem when table contains tab chars

### ISSUE THREAD

**Issue by Jaddy** [fcrespo82/atom-markdown-table-formatter#28]
Hi :)

I just tried your package and had problems to reformat an older MD doc, i.e. nothing happened at all, until I replaced all hard tabs with spaces.

Greetings,

```
Kai
```

**Comment by fcrespo82** [comment]
The hard tabs were inside the table, or outside?

**Comment by Jaddy** [comment]
The tabs were inside the table. Originally formatted with Mardown Composer, which uses tabs to beautify the plain .md view. I.e. the whitespace between cell content and following "|" were all tabs.

**Comment by fcrespo82** [comment]
I see. 

Can you please post the table with hard tabs so I can run a test?
