### ISSUE TITLE
Not working in atom 1.7.2

### ISSUE THREAD

**Issue by wizwjw** [fcrespo82/atom-markdown-table-formatter#31]
atom: 1.7.2
os: mac osx 10.11.4 

I tried both save file and select table and format, nothing happens!

**Comment by lierdakil** [comment]
Make sure you're using Markdown grammar. You can add additional grammars in package settings.

**Comment by icetee** [comment]
Atom: 1.7.3
OS: OSX 10.11.4

Perfect work!

**Comment by wizwjw** [comment]
I'm quite sure using Markdown grammar,  and also upgrade atom to 1.7.3, not working.

![image](https://cloud.githubusercontent.com/assets/1625837/15205223/0ce8d312-1848-11e6-8961-902faa66229f.png)

![image](https://cloud.githubusercontent.com/assets/1625837/15205230/1fd61ade-1848-11e6-9a2e-7396ea476a57.png)

Here is my markdown plugin list:

![image](https://cloud.githubusercontent.com/assets/1625837/15205244/367caafa-1848-11e6-9905-192a2aae11bd.png)

Is there possible of plugin collision?

**Comment by lierdakil** [comment]
Try selecting 'Github Markdown' grammar.

**Comment by wizwjw** [comment]
After uninstall the follow plugins, it worked.

```
language-markdown
markdown-preview-plus
markdown-preview-plus-opener
markdown-writer
```

**Comment by fcrespo82** [comment]
Have you tried to put `text.md` in **Markdown Grammar Scopes** configuration.
I've just installed Atom 1.7.3 on Ubuntu and all of your packages and after I put that under **Markdown Grammar Scopes** worked fine. But the alignment bug with chinese chars occurs.

**Comment by wizwjw** [comment]
I just tried to put `text.md` in **Grammar Scopes**, and It worked. @fcrespo82 Thanks for your reply.

And I'm really looking forward the chinese chars alignment problems getting handled.

**Comment by lierdakil** [comment]
@wizwjw, your Chinese font isn't monospace. It's literally impossible to fix alignment for non-monospace fonts. TL;DR it's font issue, nothing we can do on our end.

Closing as resolved.
