### ISSUE TITLE
'alt-shift-t' Keybindings not working

### ISSUE THREAD

**Issue by graphicsminded** [fcrespo82/atom-markdown-table-formatter#32]
OS: Mac OS X El Capitan 10.11.4
Atom: 1.7.3
Document is named and saved as: doc.md
Chosen Formatting (bottom right corner of Atom): .md

Your keybindings are not working. I uninstalled and re-installed, still nothing.
I took your default keybindings from your `keymaps/markdown-table-formatter.cson` and tried to make my own, still nothing.
Here is your keymap:
```
'atom-text-editor':
  'alt-shift-t': 'markdown-table-formatter:format'
```
Not working.
Here is my custom keymap from my `keymap.cson`:
```
'atom-text-editor':
  'shift-cmd-T': 'markdown-table-formatter:format'
```
Still not working.

It actually seems to me that your keymap file isn't being seen by the plugin. Your plugin doesn't have a Keybindings section like all the other plugins. It might fix it by creating a Keybindings section in the plugin settings.

Any ideas?

**Comment by lierdakil** [comment]
Check what Atom's keybinding resolver says (toggle it via command pallette, look for 'resolver')

Also check what markdown grammar you're actually using (run 'Editor: Log Cursor Scope' from command palette and check top scope)

**Comment by graphicsminded** [comment]
OK, I got it to work, but... Here we go:
When I highlight a mis-formatted table to correct it and I use your (the author et al) default keybinding from the instructions in the settings `alt-shift-t`:
```
'atom-text-editor':
  'alt-shift-t': 'markdown-table-formatter:format'
```
the resolver says `alt-shift-T` but with no specific keybinding showing up in the list of the resolver... and the table get REPLACED with a `ˇ`.

When I replace the default selector `atom-text-editor` with `.platform-darwin .editor`  in my own custom keybinding in my `keymap.cson`:
```
'.platform-darwin .editor':
  'alt-shift-t': 'markdown-table-formatter:format'
```
it works.

Apparently, the selector you have as default is not specific enough. Maybe it's because the new selector has the class dot `.` in it.

I used the principles from this thread to make this work:
https://discuss.atom.io/t/keymap-change-not-working/13839/4 

So, as it stands (at least in my environment; Atom: 1.7.3) the only way to make your plugin work with a keybinding is to create my own more-specific keybinding in my `keymap.cson`.

> This is a patch, not a fix, so I don't feel right closing this.
> What say you?
> -Scott

**Comment by lierdakil** [comment]
`.editor` selector is deprecated. New one is `atom-text-editor` actually. Topic you're referring to is from 2014, so that has changed since.

Let me update to Atom 1.7.3 and try it for myself (although, I'm on Linux, so that might not be very representative).

**Comment by lierdakil** [comment]
Works as expected on Linux. So, things to try:

- try to define 'alt-shift-T` on `atom-text-editor`. Maybe upper vs lower case matters on MacOS (I would consider this a bug in Atom)
- I might try to define platform-specific keybindings in package config. Maybe that will help.
- You might also try to reinstall the package (i.e. uninstall, then install again). Maybe something just broke subtly on initial installation (those things happen from time to time)

In all honesty, this is all a mystery to me. It should work.

**Comment by graphicsminded** [comment]
[WORKING]

For some reason, initially this plugin's Keybindings area in Settings disappeared. 

Man, I hate to say it but a hard restart of everything and a check for any updates worked.

Now the plugin's Keybindings area in Settings has re-appeared.

Thank you for your time and attention.

> FWIW, I'm glad everything is working fine on your end. - Scott
