### ISSUE TITLE
Key Combination does nothing

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [fcrespo82/atom-markdown-table-formatter#33]
I tried the following table styles:

    | Header One     | Header Two     | test|
    | :------------- | :------------- | as |
    | Item One       | Item Two       |

    +---+---+
    | aasas | a |
    +===+===+
    | a | a    |
    +---+---+

However, when I press `alt-shift-t`, nothing happens. I can mark the tables, one table of them, or none, it makes no difference, nothing happens when I press that key combination. I also added the key combination to my own key mapping - nothing.

**Comment by lierdakil** [comment]
1) Only pipe tables are supoprted
2) Make sure you're using 'Github Markdown' grammar -- by default, package only activates on that. You can add additional grammars in package settings. Run 'log scopes under cursor' (or something like that) command from command palette to see current grammar identifier (it will be on top of pop-up message)

**Comment by ZelphirKaltstahl** [comment]
@lierdakil Isn't the first one a pipe table?

When I issue the comment "Editor Log Cursor Scope", I see a blue box, in which it reads

    Scopes at Cursor

    source.gfm
    table.gfm

So I guess the Github Flavoured Markdown is active?

**Comment by lierdakil** [comment]
Technically it isn't. Try this:

```
|Header One|Header Two| test|
|-|-|-|
|Item One|Item Two|as|
```

**Comment by lierdakil** [comment]
And yes, grammar is correct.

**Comment by fcrespo82** [comment]
Hi @ZelphirKaltstahl 

@lierdakil was talking about the second table.

Now about the first table. It is misconstructed, the last column don't have a header alignment line. This should be the reason it is not working. I tested in my setup and worked when I added the line

```
| Header One     | Header Two     | test|
| :------------- | :------------- | - |
| Item One       | Item Two       | as |
```

**Comment by ZelphirKaltstahl** [comment]
Haha, sometimes one can be really blind to such mistakes! Thanks, it works now. Grid table would be good to have as well, but at least the alignment pipe tables work, so that's good already. There is a sublime text plugin, which handles grid tables and I am still searching for such an atom package.

**Comment by lierdakil** [comment]
PRs are welcome. Can't say about @fcrespo82, but I don't have much time to devote to grid table support right now. Closing this as resolved, and creating https://github.com/fcrespo82/atom-markdown-table-formatter/issues/34 for grid tables.
