### ISSUE TITLE
Doesn't work at all in Mac OS X 10.11.6, Atom version 1.8.0 

### ISSUE THREAD

**Issue by Granfalloner** [fcrespo82/atom-markdown-table-formatter#35]
Command simply ignored no matter how I invoke it (with or without selecting table, including empty lines around table in selection or not, etc). Tried on different documents - doesn't work even in case when file contains only one table.

**Comment by Granfalloner** [comment]
Found out the problem - it was incorrect grammar scope for document. I would suggest to add the following info to README.md to help other users (copied from Spell Check readme):

> To enable Spell Check for your current file type: put your cursor in the file, open the Command Palette (cmd-shift-p), and run the Editor: Log Cursor Scope command. This will trigger a notification which will contain a list of scopes. The first scope that's listed is the one you should add to the list of scopes in the settings for the Spell Check package.

**Comment by fcrespo82** [comment]
Awesome addition. Thanks! Added to README.
