### ISSUE TITLE
Doesn't work what so ever

### ISSUE THREAD

**Issue by Olian04** [fcrespo82/atom-markdown-table-formatter#37]
I'm not sure why, but nothing happens. 
I've tried both `alt-shift-t` as well as executing the command via the command pallet, but neither does anything.

**Comment by lierdakil** [comment]
Could you please provide output of 'atom --version'?

28 окт. 2016 г. 5:20 ПП пользователь "Oliver Anteros" <
notifications@github.com> написал:

**Comment by dwelle** [comment]
@Olian04 does the file have `markdown` grammar? AFAIK only works with that.

**Comment by Olian04** [comment]
`atom --version`:
>Atom    : 1.9.9
>Electron: 0.37.8
>Chrome  : 49.0.2623.75
>Node    : 5.10.0

Grammar used: [burodepeper/language-markdown](https://github.com/burodepeper/language-markdown)

**Comment by lierdakil** [comment]
Try adding 'text.md' (without quotes) scope to 'markdownGrammarScopes'
setting of this package. See
https://github.com/fcrespo82/atom-markdown-table-formatter#settings--keybindings
and below for details.

**Comment by Olian04** [comment]
@lierdakil hmmm, that did it...
Why?

**Comment by lierdakil** [comment]
Default markdown grammar in Atom uses `source.gfm` scope. This package detects if it should trigger for a given editor based on scope. Package you've referenced defines Markdown files as `text.md` scope instead. https://github.com/fcrespo82/atom-markdown-table-formatter#enable-markdown-table-formatter-for-the-current-file-type

You can thank @dwelle for asking the right question. If not for that, I would probably ask for a list of installed packages next (`apm list -b`).

**Comment by Olian04** [comment]
@lierdakil alright, cool. Thanks :)
