### ISSUE TITLE
Format current table?

### ISSUE THREAD

**Issue by rauschma** [fcrespo82/atom-markdown-table-formatter#42]
Thanks for this package!

How about providing the option to format the table one is currently in if nothing is selected?

* You could edit and format at the same time. No need to select the table first (which is slightly time-consuming).
* If you want to format the whole document then that can still be done quickly (via “select all” and formatting).

**Comment by lierdakil** [comment]
I'm pretty sure that's how it works currently, at least if 'Auto Select Entire Document' is *not* enabled... At least if your current grammar scope is added to what package recognizes as Markdown.

**Comment by fcrespo82** [comment]
I found some odd behavior on the Atom (1.23.3 x64 linux) side that can be causing the confusion and misinformation about the settings of this package.
If you go to Packages and to the **Markdown table formatter** page, the settings doesn't show. To find the settings you have to go to **Install** -> **Search for the package** -> **click in settings**, which for me is a little weird.
