### ISSUE TITLE
Table formatter does not format

### ISSUE THREAD

**Issue by PavelVanecek** [fcrespo82/atom-markdown-table-formatter#44]
When I attempt to format a Markdown table, nothing happens. There are no errors, no popups, console is empty.

I tried to follow steps from #31 and #35 and #37. My document grammar is "GitHub Markdown", cursor scope is `source.gfm` and `table.gfm`. I tried adding `text.md`, no change.

I tried to reinstall the plugin, no help. I remember it worked some months ago, not sure when it stopped.

Can you please advice next steps?

```
$ atom --version
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

OSX 10.12.6
markdown-table-formatter 2.9.0

**Comment by fcrespo82** [comment]
I was able to reproduce this.

I need more tests but the problem is that the `editor` is not defined.

markdown-table-formatter.coffee ( line 53)
```coffee
editor = event?.target?.getModel?()
```
